# IMAGES - Arranged by character

# BACKGROUND
image bg test1 = "bg_test1.png"
image bg abyss = "BG - Abyss.jpg"
image bg alley = "BG - Alley.jpg"
image bg apartment night = "BG - Apartment (Night).jpg"
image bg bedroom = "BG - Bedroom.jpg"
image bg blood = "BG - Blood.jpg"
image bg blood2 = "BG - Blood 2.jpg"
image bg book = "BG - Book.jpg"
image bg chemistrylab = "BG - Chemistry Lab.jpg"
image bg church = "BG - Church.jpg"
image bg classroom1 = "BG - Classroom1.jpg"
image bg classroom1 morning = "BG - Classroom1 (Morning).jpg"
image bg classroom2 = "BG - Classroom2.jpg"
image bg classroom2 morning = "BG - Classroom2 (Morning).jpg"
image bg clinic = "BG - Clinic.jpg"
image bg cowpainting = "BG - Cow Painting.jpg"
image bg darkalley = "BG - Dark Alley.jpg"
image bg darkhallway = "BG - Dark Hallway.jpg"
image bg darkhallway2 = "BG - Dark Hallway 2.jpg"
image bg darkhallway3 = "BG - Dark Hallway 3.jpg"
image bg darkhallway3 nightmare = "BG - Dark Hallway 3 (Nightmare).jpg"
image bg diningroom = "BG - Dining Room.jpeg"
image bg eatery = "BG - Eatery.jpg"
image bg emptycell = "BG - Empty Cell.jpg"
image bg emptycell2 = "BG - Empty Cell 2.jpg"
image bg envelopefour = "BG - EnvelopeFour.jpg"
image bg eyesdark = "BG - Eyes Dark.jpg"
image bg facultyroom = "BG - Faculty Room.jpg"
image bg fire = "BG - Fire.jpg"
image bg freedompark = "BG - Freedom Park.jpg"
image bg freedompark night = "BG - Freedom Park (Night).jpg"
image bg functionroom = "BG - Function Room.jpg"
image bg hands suzumoto = "BG - Hands (Suzumoto).jpg"
image bg hdml1347 = "BG - HDML 1347.jpg"
image bg kitchen = "BG - Kitchen.jpg"
image bg labdoor = "BG - Lab Door.jpg"
image bg letter a = "BG - LetterA.jpg"
image bg letter b = "BG - LetterB.jpg"
image bg livingroom = "BG - Living Room.jpg"
image bg longhallway = "BG - Long Hallway.jpg"
image bg meadow = "BG - Meadow.jpg"
image bg ministryroom = "BG - Ministry Room.jpg"
image bg minotaur = "BG - Minotaur.jpg"
image bg moon = "BG - Moon.jpg"
image bg msci = "BG - MSCI.jpg"
image bg msci evening = "BG - MSCI (Evening).jpg"
image bg msci night = "BG - MSCI (Night).jpg"
image bg msci nightmare = "BG - MSCI (Nightmare).jpg"
image bg parlor = "BG - Parlor.jpg"
image bg pasteur night = "BG - Pasteur (Night).jpg"
image bg pool = "BG - Pool.jpg"
image bg pool nightmare = "BG - Pool (Nightmare).jpg"
image bg principalsoffice = "BG - Principal's Office.jpg"
image bg receptiondesk = "BG - Reception Desk.jpg"
image bg roulette = "BG - Roulette.jpg"
image bg school fields = "BG - School Fields.jpg"
image bg school fields evening = "BG - School Fields (Evening).jpg"
image bg school fields night = "BG - School Fields (Night).jpg"
image bg school gate = "BG - School Gate.jpg"
image bg school gate evening = "BG - School Gate (Evening).jpg"
image bg school gate morning = "BG - School Gate (Morning).jpg"
image bg school hallway = "BG - School Hallway.jpg"
image bg school outside = "BG - School Outside.jpg"
image bg splashscreen = "BG - Splash Screen.png"
image bg storageroom = "BG - Storage Room.jpg"
image bg street night = "BG - Street (Night).jpg"
image bg street rain = "BG - Street (Rain).jpg"
image bg tvstatic = "BG - TV Static.jpg"
image bg underwater = "BG - Underwater.jpg"
image bg underwater nightmare = "BG - Underwater (Nightmare).jpg"
image bg van = "BG - Van.jpg"
image bg village = "BG - Village.jpg"
image bg village night = "BG - Village (Night).jpg"
image bg wetmarket = "BG - Wet Market.jpg"
image bg wetmarket night = "BG - Wet Market (Night).jpg"
image red = "BG - Red.jpg"
image white = "BG - White.jpg"
image op title1 = "Opening - Title1.png"
image op title2 = "Opening - Title2.png"
image op roulette = "Opening - Roulette.jpg"
image op sayo = "Opening - Sayo.png"
image op hikaru = "Opening - Hikaru.png"
image op inoue = "Opening - Inoue.png"
image op miyu = "Opening - Miyu.png"
image op ichirou = "Opening - Ichirou.png"
image op yoshiro = "Opening - Yoshiro.png"
image op akira = "Opening - Akira.png"
image op sumiko = "Opening - Sumiko.png"
image op hiroshi = "Opening - Hiroshi.png"
image op kyou = "Opening - Kyou.png"

###=========###
# MAIN
###=========###

# Sayo Ronoroa
image sayo blankface = "sayo_blank_face.png"
image sayo happyclosed = "sayo_happy_closed.png"
image sayo happytalk = "sayo_happy_talk.png"
image sayo happytalkblush = "sayo_happy_talk_blush.png"
image sayo normaltalk = "sayo_normal_talk.png"
image sayo normaltalkleft = "sayo_normal_talk_left.png"
image sayo seriousclosed = "sayo_serious_closed.png"
image sayo seriousnormal = "sayo_serious_normal.png"
image sayo seriousnormalleft = "sayo_serious_normal_left.png"
image sayo seriousserious = "sayo_serious_serious.png"
image sayo serioustalk = "sayo_serious_talk.png"
image sayo serioustalkleft = "sayo_serious_talk_left.png"
image sayo serioustalk2 = "sayo_serious_talk2.png"
image sayo smileclosed = "sayo_smile_closed.png"
image sayo smileopen = "sayo_smile_open.png"
image sayo smileopen2 = "sayo_smile_open2.png"
image sayo smiletalk = "sayo_smile_talk.png"
image sayo smirkblush = "sayo_smirk_blush.png"
image sayo smirknormal = "sayo_smirk_normal.png"
image sayo upset = "sayo_upset.png"
image sayo upsetcry = "sayo_upset_cry.png"
image sayo worried = "sayo_worried.png"
image sayo worriedtalk = "sayo_worried_talk.png"
image sayo worriedtalkclosed = "sayo_worried_talk_closed.png"
image sayo worriedtalkcry = "sayo_worried_talk_cry.png"
image sayo casual glass normaltalk = "sayocasual_glass_normal_talk.png"
image sayo casual glass normaltalkleft = "sayocasual_glass_normal_talk_left.png"
image sayo casual glass serious = "sayocasual_glass_serious.png"
image sayo casual glass seriousleft = "sayocasual_glass_serious_left.png"
image sayo casual glass serioustalk = "sayocasual_glass_serious_talk.png"
image sayo casual glass serioustalkleft = "sayocasual_glass_serious_talk_left.png"
image sayo casual glass smile = "sayocasual_glass_smile.png"
image sayo casual glass smileclosed = "sayocasual_glass_smile_closed.png"
image sayo casual glass smiletalk = "sayocasual_glass_smile_talk.png"
image sayo casual glass smile2 = "sayocasual_glass_smile2.png"

# Hikaru Yamamoto
image hikaru angry = "hikaru_angry.png"
image hikaru blush = "hikaru_blush.png"
image hikaru focusleft = "hikaru_focus_left.png"
image hikaru focusright = "hikaru_focus_right.png"
image hikaru naughty = "hikaru_naughty.png"
image hikaru pissed = "hikaru_pissed.png"
image hikaru serious = "hikaru_serious.png"
image hikaru smile = "hikaru_smile.png"
image hikaru smirk = "hikaru_smirk.png"
image hikaru talk = "hikaru_talk.png"
image hikaru worried = "hikaru_worried.png"

# Inoue Shinozaki
image inoue blank = "inoue_blank.png"
image inoue creepy blank = "inoue_creepy_blank.png"
image inoue creepy blood angry = "inoue_creepy_blood_angry.png"
image inoue creepy blood snap = "inoue_creepy_blood_snap.png"
image inoue creepy blood snap2 = "inoue_creepy_blood_snap2.png"
image inoue creepy focused = "inoue_creepy_focused.png"
image inoue creepy focusedpose = "inoue_creepy_focused_pose.png"
image inoue creepy serious = "inoue_creepy_serious.png"
image inoue creepy smile = "inoue_creepy_smile.png"
image inoue creepy smile2 = "inoue_creepy_smile2.png"
image inoue creepy smile3 = "inoue_creepy_smile3.png"
image inoue creepy smirk = "inoue_creepy_smirk.png"
image inoue creepy smirkpose = "inoue_creepy_smirk_pose.png"
image inoue dullsurprise = "inoue_dull_surprise.png"
image inoue happyclosed = "inoue_happy_closed.png"
image inoue happyopen = "inoue_happy_open.png"
image inoue happypose = "inoue_happy_pose.png"
image inoue noglass angry = "inoue_noglass_angry.png"
image inoue noglass angrycry = "inoue_noglass_angrycry.png"
image inoue noglass blood cry = "inoue_noglass_blood_cry.png"
image inoue noglass blood cry2 = "inoue_noglass_blood_cry2.png"
image inoue noglass blood sad = "inoue_noglass_blood_sad.png"
image inoue noglass cry = "inoue_noglass_cry.png"
image inoue noglass happytalk = "inoue_noglass_happy_talk.png"
image inoue noglass laughcry = "inoue_noglass_laughcry.png"
image inoue noglass pissed = "inoue_noglass_pissed.png"
image inoue noglass sad = "inoue_noglass_sad.png"
image inoue noglass sadcry = "inoue_noglass_sad_cry.png"
image inoue noglass sadcry2 = "inoue_noglass_sad_cry2.png"
image inoue noglass sadleft = "inoue_noglass_sad_left.png"
image inoue noglass serious = "inoue_noglass_serious.png"
image inoue noglass serious2 = "inoue_noglass_serious2.png"
image inoue noglass smilecry = "inoue_noglass_smilecry.png"
image inoue noglass talk = "inoue_noglass_talk.png"
image inoue noglass talk2 = "inoue_noglass_talk2.png"
image inoue noglass worried = "inoue_noglass_worried.png"
image inoue noglass proud = "inoue_proud.png"
image inoue schemingclosed = "inoue_scheming_closed.png"
image inoue schemingopen = "inoue_scheming_open.png"
image inoue serious = "inoue_serious.png"
image inoue seriousleft = "inoue_serious_left.png"
image inoue seriouspose = "inoue_serious_pose.png"
image inoue serioustalk = "inoue_serious_talk.png"
image inoue serioustalk2 = "inoue_serious_talk2.png"
image inoue sigh = "inoue_sigh.png"
image inoue sighclosed = "inoue_sigh_closed.png"
image inoue smile = "inoue_smile.png"
image inoue smilepose = "inoue_smile_pose.png"
image inoue surprised = "inoue_surprised.png"
image inoue talk = "inoue_talk.png"
image inoue worried = "inoue_worried.png"
image inoue worriedpose = "inoue_worried_pose.png"
image inoue casual blank = "inouecasual_blank.png"
image inoue casual confused = "inouecasual_confused.png"
image inoue casual confusedtalk = "inouecasual_confused_talk.png"
image inoue casual determined = "inouecasual_determined.png"
image inoue casual serious = "inouecasual_serious.png"
image inoue casual seriouspose = "inouecasual_serious_pose.png"
image inoue casual serioustalk = "inouecasual_serious_talk.png"
image inoue casual serioustalk2 = "inouecasual_serious_talk2.png"
image inoue casual serioustalk3 = "inouecasual_serious_talk3.png"
image inoue casual sigh = "inouecasual_sigh.png"
image inoue casual sighpose = "inouecasual_sigh_pose.png"
image inoue casual smile = "inouecasual_smile.png"
image inoue casual surprised = "inouecasual_surprised.png"
image inoue casual troubled = "inouecasual_troubled.png"
image inoue casual troubledtalk = "inouecasual_troubled_talk.png"
image inoue casual worriedpose = "inouecasual_worried_pose.png"

# Miyu Hirano
image miyu bored = "miyu_bored.png"
image miyu confused = "miyu_confused.png"
image miyu embarassed = "miyu_embarassed.png"
image miyu focusedpose = "miyu_focused_pose.png"
image miyu happytalk = "miyu_happy_talk.png"
image miyu naughty blush = "miyu_naughty_blush.png"
image miyu naughty closepose = "miyu_naughty_close_pose.png"
image miyu naughty closepose2 = "miyu_naughty_close_pose2.png"
image miyu naughty focuspose = "miyu_naughty_focus_pose.png"
image miyu naughty focuspose2 = "miyu_naughty_focus_pose2.png"
image miyu naughty smile = "miyu_naughty_smile.png"
image miyu naughty smirk = "miyu_naughty_smirk.png"
image miyu naughty smirkpose = "miyu_naughty_smirk_pose.png"
image miyu naughty talk = "miyu_naughty_talk.png"
image miyu pissed = "miyu_pissed.png"
image miyu pissedclosed = "miyu_pissed_closed.png"
image miyu proudclosed = "miyu_proud_closed.png"
image miyu serious = "miyu_serious.png"
image miyu smile = "miyu_smile.png"
image miyu surprised = "miyu_surprised.png"
image miyu talk = "miyu_talk.png"
image miyu worried = "miyu_worried.png"

# Ichirou Yokohama
image ichirou confused = "ichirou_confused.png"
image ichirou embarassed = "ichirou_embarassed.png"
image ichirou focus = "ichirou_focus.png"
image ichirou focusleft = "ichirou_focus_left.png"
image ichirou happy = "ichirou_happy.png"
image ichirou happyblush = "ichirou_happy_blush.png"
image ichirou happy2 = "ichirou_happy2.png"
image ichirou proud = "ichirou_proud.png"
image ichirou serious = "ichirou_serious.png"
image ichirou smile = "ichirou_smile.png"
image ichirou surprised = "ichirou_surprised.png"
image ichirou worried = "ichirou_worried.png"
image ichirou casual blank = "ichiroucasual_blank.png"
image ichirou casual focus = "ichiroucasual_focus.png"
image ichirou casual happy = "ichiroucasual_happy.png"
image ichirou casual proud = "ichiroucasual_proud.png"
image ichirou casual smile = "ichiroucasual_smile.png"
image ichirou casual smileleft = "ichiroucasual_smile_left.png"
image ichirou casual smirk = "ichiroucasual_smirk.png"
image ichirou casual surprised = "ichiroucasual_surprised.png"

# Yoshiro Suzuki
image yoshiro angry = "yoshiro_angry.png"
image yoshiro serious = "yoshiro_serious.png"
image yoshiro serious2 = "yoshiro_serious2.png"
image yoshiro smile = "yoshiro_smile.png"
image yoshiro smirk = "yoshiro_smirk.png"
image yoshiro smirkclosed = "yoshiro_smirk_closed.png"
image yoshiro surprised = "yoshiro_surprised.png"
image yoshiro surprised2 = "yoshiro_surprised2.png"
image yoshiro talkleft = "yoshiro_talk_left.png"
image yoshiro worried = "yoshiro_worried.png"
image yoshiro worriedleft = "yoshiro_worried_left.png"

# Akira Ichibana
image akira angry = "akira_angry.png"
image akira annoyed = "akira_annoyed.png"
image akira annoyedclosed = "akira_annoyed_closed.png"
image akira fang = "akira_fang.png"
image akira fangblush = "akira_fang_blush.png"
image akira happy = "akira_happy.png"
image akira proud = "akira_proud.png"
image akira proudclosed = "akira_proud_closed.png"
image akira proud2 = "akira_proud2.png"
image akira serious = "akira_serious.png"
image akira smile = "akira_smile.png"
image akira smileleft = "akira_smile_left.png"
image akira smile2 = "akira_smile2.png"
image akira smirk = "akira_smirk.png"
image akira surprised = "akira_surprised.png"
image akira surprised2 = "akira_surprised2.png"
image akira worried = "akira_worried.png"
image akira worriedleft = "akira_worried_left.png"

# Sumiko Tokubei
image sumiko angry = "sumiko_angry.png"
image sumiko serious = "sumiko_serious.png"
image sumiko seriousleft = "sumiko_serious_left.png"
image sumiko serioustalk = "sumiko_serious_talk.png"
image sumiko sighclosed = "sumiko_sigh_closed.png"
image sumiko smile = "sumiko_smile.png"
image sumiko smirk = "sumiko_smirk.png"
image sumiko smirkclosed = "sumiko_smirk_closed.png"
image sumiko surprised = "sumiko_surprised.png"
image sumiko surprisedtalk = "sumiko_surprised_talk.png"
image sumiko surprised2 = "sumiko_surprised2.png"

# Hiroshi Kano
image hiroshi bored = "hiroshi_bored.png"
image hiroshi boredleft = "hiroshi_bored_left.png"
image hiroshi boredtalk = "hiroshi_bored_talk.png"
image hiroshi determined = "hiroshi_determined.png"
image hiroshi determined2 = "hiroshi_determined2.png"
image hiroshi happyblush = "hiroshi_happy_blush.png"
image hiroshi smile = "hiroshi_smile.png"
image hiroshi smileleft = "hiroshi_smile_left.png"
image hiroshi smile2 = "hiroshi_smile2.png"
image hiroshi worried = "hiroshi_worried.png"
image hiroshi worriedleft = "hiroshi_worried_left.png"

# Kyou Kirisaki
image kyou angryleft = "kyou_angry_left.png"
image kyou angrytalk = "kyou_angry_talk.png"
image kyou blood angry = "kyou_blood_angry.png"
image kyou blood angryclosed = "kyou_blood_angry_closed.png"
image kyou blood dull angry = "kyou_blood_dull_angry.png"
image kyou blood dull sad = "kyou_blood_dull_sad.png"
image kyou blood dull surprised = "kyou_blood_dull_surprised.png"
image kyou blood happy = "kyou_blood_happy.png"
image kyou blood hurt = "kyou_blood_hurt.png"
image kyou blood serious = "kyou_blood_serious.png"
image kyou blood smirk = "kyou_blood_smirk.png"
image kyou blood worriedleft = "kyou_blood_worried_left.png"
image kyou calmclosedcry = "kyou_calm_closed_cry.png"
image kyou calmleft = "kyou_calm_left.png"
image kyou confused = "kyou_confused.png"
image kyou confusedtalk = "kyou_confused_talk.png"
image kyou confused2 = "kyou_confused2.png"
image kyou focusleft = "kyou_focus_left.png"
image kyou happy = "kyou_happy.png"
image kyou happyclosed = "kyou_happy_closed.png"
image kyou proud = "kyou_proud.png"
image kyou sad = "kyou_sad.png"
image kyou sad2 = "kyou_sad2.png"
image kyou serious = "kyou_serious.png"
image kyou serious2 = "kyou_serious2.png"
image kyou serious leftpose = "kyou_serious_left_pose.png"
image kyou serious pose = "kyou_serious_pose.png"
image kyou serious smile = "kyou_serious_smile.png"
image kyou serious smileclosedpose = "kyou_serious_smile_closed_pose.png"
image kyou serious smilepose = "kyou_serious_smile_pose.png"
image kyou serious smile2 = "kyou_serious_smile2.png"
image kyou serious talk = "kyou_serious_talk.png"
image kyou smile = "kyou_smile.png"
image kyou smileleft = "kyou_smile_left.png"
image kyou smirk = "kyou_smirk.png"
image kyou smirk2 = "kyou_smirk2.png"
image kyou surprisedleft = "kyou_surprised_left.png"
image kyou surprisedleft2 = "kyou_surprised_left2.png"
image kyou surprisedtalk = "kyou_surprised_talk.png"
image kyou surprised2 = "kyou_surprised2.png"
image kyou worried = "kyou_worried.png"
image kyou worriedclosed = "kyou_worried_closed.png"
image kyou worriedleft = "kyou_worried_left.png"
image kyou worried2 = "kyou_worried2.png"

###=========###
# SIDE
###=========###

image ikuko casual blank = "ikukocasual_blank.png"
image ikuko casual happy = "ikukocasual_happy.png"
image ikuko casual smile = "ikukocasual_smile.png"
image ikuko casual smiletalk = "ikukocasual_smile_talk.png"
image ikuko casual smirk = "ikukocasual_smirk.png"
image ikuko casual talk = "ikukocasual_talk.png"

image emmerich angry = "emmerich_angry.png"
image emmerich serious = "emmerich_serious.png"
image emmerich seriousclosed = "emmerich_serious_closed.png"
image emmerich smile = "emmerich_smile.png"
image emmerich smileteeth = "emmerich_smile_teeth.png"
image emmerich smile2 = "emmerich_smile2.png"
image emmerich smirk = "emmerich_smirk.png"
image emmerich smirkleft = "emmerich_smirk_left.png"
image emmerich smirk2 = "emmerich_smirk2.png"
image emmerich talk = "emmerich_talk.png"
image emmerich worried = "emmerich_worried.png"

image silhouette = "silhouette.png"

# MUSIC

###=========###
# BGM
###=========###

define audio.bg_calmertimes = "music/Eric Matyas - Calmer Times.mp3"
define audio.bg_hazydisorientation = "music/Eric Matyas - Hazy Disorientation.mp3"
define audio.bg_onthingstocome = "music/Eric Matyas - On Things to Come.mp3"
define audio.bg_theanthillganggoeswest = "music/Eric Matyas - The Ant Hill Gang Goes West.mp3"
define audio.bg_autumnday = "music/Kevin MacLeod - Autumn Day.mp3"
define audio.bg_awkwardmeeting = "music/Kevin MacLeod - Awkward Meeting.mp3"
define audio.bg_corruption = "music/Kevin MacLeod - Corruption.mp3"
define audio.bg_controlledchaos = "music/Kevin MacLeod - Controlled Chaos.mp3"
define audio.bg_decline = "music/Kevin MacLeod - Decline.mp3"
define audio.bg_echoesoftime = "music/Kevin MacLeod - Echoes of Time.mp3"
define audio.bg_ghoststory = "music/Kevin MacLeod - Ghost Story.mp3"
define audio.bg_merrygo = "music/Kevin MacLeod - Merry Go.mp3"
define audio.bg_nightofchaos = "music/Kevin MacLeod - Night of Chaos.mp3"
define audio.bg_porchswingdays = "music/Kevin MacLeod - Porch Swing Days.mp3"
define audio.bg_roadtohell = "music/Kevin MacLeod - Road To Hell.mp3"
define audio.bg_satiate = "music/Kevin MacLeod - Satiate.mp3"
define audio.bg_twotogether = "music/Kevin MacLeod - Two Together.mp3"
define audio.bg_undaunted = "music/Kevin MacLeod - Undaunted.mp3"
define audio.bg_vulcan = "music/Kevin MacLeod - Vulcan.mp3"
define audio.bg_chloeslullaby = "music/Robert Austin - Chloe's Lullaby.mp3"
define audio.bg_ringaroundtherosie = "music/Rhyme - Ring Around The Rosie (Short).ogg"
define audio.bg_auclairdelalune = "music/Au Clair de La Lune.ogg"

###=========###
# SFX
###=========###

define audio.sfx_ambulance = "music/ambulance.ogg"
define audio.sfx_ambulance1 = "music/ambulance1.ogg"
define audio.sfx_ambulance2 = "music/ambulance2.ogg"
define audio.sfx_applause = "music/applause.ogg"
define audio.sfx_beep = "music/beep.ogg"
define audio.sfx_breathing = "music/breathing.ogg"
define audio.sfx_chain = "music/chain.ogg"
define audio.sfx_chirp = "music/chirp.ogg"
define audio.sfx_clang = "music/clang.ogg"
define audio.sfx_clockbell = "music/clockbell.ogg"
define audio.sfx_crickets = "music/crickets.ogg"
define audio.sfx_click = "music/Eric Matyas - UI_Quirky18.mp3"
define audio.sfx_doorknob = "music/doorknob.ogg"
define audio.sfx_dooropen = "music/dooropen.ogg"
define audio.sfx_ekg = "music/ekg.ogg"
define audio.sfx_ekg2 = "music/ekg2.ogg"
define audio.sfx_explosion = "music/explosion.ogg"
define audio.sfx_fire = "music/fire.ogg"
define audio.sfx_fire2 = "music/fire2.ogg"
define audio.sfx_fire3 = "music/fire3.ogg"
define audio.sfx_footsteps = "music/footsteps.ogg"
define audio.sfx_footsteps2 = "music/footsteps2.ogg"
define audio.sfx_footsteps3 = "music/footsteps3.ogg"
define audio.sfx_giggle = "music/giggle.ogg"
define audio.sfx_girlcry = "music/girlcry.ogg"
define audio.sfx_glass = "music/glass.ogg"
define audio.sfx_growl = "music/growl.ogg"
define audio.sfx_handbell = "music/handbell.ogg"
define audio.sfx_hangup = "music/hangup.ogg"
define audio.sfx_heartbeat = "music/heartbeat.ogg"
define audio.sfx_hiss = "music/hiss.ogg"
define audio.sfx_knock = "music/knock.ogg"
define audio.sfx_metaldrop = "music/metaldrop.ogg"
define audio.sfx_pageturn = "music/pageturn.ogg"
define audio.sfx_phonering = "music/phonering.ogg"
define audio.sfx_rain = "music/rain.ogg"
define audio.sfx_revolver = "music/revolver.ogg"
define audio.sfx_ringtone = "music/ringtone.ogg"
define audio.sfx_roulette = "music/roulette.ogg"
define audio.sfx_rubikscube = "music/rubikscube.ogg"
define audio.sfx_rumble = "music/rumble.ogg"
define audio.sfx_spark = "music/spark.ogg"
define audio.sfx_splash = "music/splash.ogg"
define audio.sfx_splash2 = "music/splash2.ogg"
define audio.sfx_splatter = "music/splatter.ogg"
define audio.sfx_static = "music/static.ogg"
define audio.sfx_static2 = "music/static2.ogg"
define audio.sfx_street = "music/Eric Matyas - Street Ambience 5 (SE).mp3"
define audio.sfx_thud = "music/thud.ogg"
define audio.sfx_thud2 = "music/thud2.ogg"
define audio.sfx_ticktock = "music/ticktock.ogg"
define audio.sfx_waterdrip = "music/waterdrip.ogg"
define audio.sfx_wind = "music/wind.ogg"

###=========###
# GUEST (COPYRIGHTED) - From other games/anime; Exclusive Copies ONLY! 
###=========###

define audio.guest_chikai = "music/Guest - Chikai (Opening).mp3"
define audio.guest_corpseparty = "music/Guest - Corpse Party.mp3"
define audio.guest_whyorwhynot = "music/Guest - Why or Why Not.mp3"